name: Fameve site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the fameve/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/fameve -v ${{ github.workspace }}/_site:/srv/fameve/_site \
        fameve/builder:latest /bin/bash -c "chmod -R 777 /srv/fameve && fameve build --future"
